### GET Root Index --> Successful test: check response status is 200
GET http://localhost:8080/
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

%}
